### ISSUE TITLE
An error occurs for responses with status code 501

### ISSUE THREAD

**Issue by equeraltowenea** [japa/errors-printer#1]
When trying to verify that a route returns us a status code 501, the following error occurs:
```
   Cannot use 'in' operator to search for 'actual' in

   at ErrorsPrinter.printError C:/testProject/node_modules/@japa/errors-printer/build/src/Printer/index.js:111
    106|      }
    107|      /**
    108|       * Pretty print the error to the console
    109|       */
    110|      async printError(error) {
  > 111|          if ('actual' in error && 'expected' in error) {
    112|              await this.displayAssertionError(error);
    113|              return;
    114|          }
    115|          if ('matcherResult' in error) {
    116|              await this.displayJestError(error);
```

This is how I tried to test this logic:
```
test('PUT /test (NOT IMPLEMENTED)', async ({ client }) => {
    // given
    const token = 'testToken'
    
    const body = {
        test: 'test'
    }
    
    // when
    const response = await client.put(`/test`)
            .json(body)
            .header('Authorization', `Token ${token}`)
    
    // then
    response.assertStatus(501)
})
```

When trying to capture the error in the catch, only an undefined is returned.

**Comment by thetutlage** [comment]
Thanks for reporting. A part of this is expected and the other part seems like a bug. Lemme try to reproduce it and then come back with a proper answer :)

**Comment by thetutlage** [comment]
Alright. So there are two things

- First, any error status code > 500 results in an exception. This is because 500 is usually not part of standard request flow. It happens when there is a fatal error on the server.

  For tests that are expecting status code > 500, you will have to wrap them inside a `try/catch` block.

  ```ts
  try {
    await client.put(`/test`)
  } catch (error) {
    console.log(error)
  }
  ```

- Second was the incorrect error handling for cases where a non-object error value was passed to `printError` method. I have fixed that part
